on: push
name: Slack Notification
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()  # jobの成否に関わらずSlackへ通知
        with:
          type: ${{ job.status }}  # jobの成否を代入(Failure/Success)
          job_name: '*CI Start*'
          channel: '#lavideo'
          icon_emoji: :bear:
        env:
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
