on: push
name: Slack Notification
jobs:
  build:
    name: Build Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()  # jobの成否に関わらずSlackへ通知
        with:
          type: ${{ job.status }}  # jobの成否を代入(Failure/Success)
          job_name: '*CI Start*'
          channel: '#lavideo'
          icon_emoji: ':bear:'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
